import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Poppins
const inter = Inter({

  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Adjust weights as needed

});

export const metadata: Metadata = {
  title: "Iconic Group 2",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
    <body>
    {children}
    </body>
    </html>
  );
}
